# Generated by Django 5.2.6 on 2025-11-22 15:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Approval Type",
                "verbose_name_plural": "Approval Types",
                "db_table": "core_approval_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
                ("decimal_places", models.IntegerField(default=2)),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False, help_text="Is this the base/home currency"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "core_currency",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ERPDocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Document type code (e.g., PR, PO, GRN, TO)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Document type name", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "erp_system",
                    models.CharField(
                        default="Microsoft Dynamics",
                        help_text="ERP system name",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ERP Document Type",
                "verbose_name_plural": "ERP Document Types",
                "db_table": "core_erp_document_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LossOfSaleCause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stockout", "Stock Out"),
                            ("breakdown", "Equipment Breakdown"),
                            ("delay", "Production Delay"),
                            ("quality", "Quality Issue"),
                            ("logistics", "Logistics Issue"),
                            ("external", "External Factor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Loss of Sale Cause",
                "verbose_name_plural": "Loss of Sale Causes",
                "db_table": "core_loss_of_sale_cause",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("high_contrast", "High Contrast"),
                        ],
                        default="light",
                        help_text="UI theme preference",
                        max_length=20,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("normal", "Normal"),
                            ("large", "Large"),
                        ],
                        default="normal",
                        help_text="Text size preference",
                        max_length=10,
                    ),
                ),
                (
                    "table_density",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("normal", "Normal"),
                            ("relaxed", "Relaxed"),
                        ],
                        default="normal",
                        help_text="Table row spacing preference",
                        max_length=10,
                    ),
                ),
                (
                    "default_landing_page",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL name of preferred landing page after login",
                        max_length=100,
                    ),
                ),
                (
                    "table_columns_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores column visibility preferences per table view",
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                (
                    "sidebar_sections",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores expanded/collapsed state of sidebar sections",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "core_user_preference",
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Cost center code (e.g., CC-001, PROD-01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Cost center name", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of cost center purpose"
                    ),
                ),
                (
                    "erp_cost_center_code",
                    models.CharField(
                        blank=True,
                        help_text="ERP system cost center code",
                        max_length=50,
                    ),
                ),
                (
                    "annual_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual budget allocation",
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for this cost center",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_cost_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent cost center for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core_foundation.costcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Center",
                "verbose_name_plural": "Cost Centers",
                "db_table": "core_cost_center",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="HR Position ID with approval authority",
                        null=True,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum amount for this approval authority",
                        max_digits=15,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount (null = unlimited)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Lower number = higher priority in routing"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group with approval authority",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_authorities",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user with approval authority",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_authorities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approval_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorities",
                        to="core_foundation.approvaltype",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit authority to specific cost center",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_authorities",
                        to="core_foundation.costcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Authority",
                "verbose_name_plural": "Approval Authorities",
                "db_table": "core_approval_authority",
                "ordering": ["approval_type", "priority"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("VIEW", "Viewed"),
                            ("EXPORT", "Exported"),
                            ("IMPORT", "Imported"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("SUBMIT", "Submitted"),
                            ("CANCEL", "Cancelled"),
                            ("COMPLETE", "Completed"),
                            ("ASSIGN", "Assigned"),
                            ("COMMENT", "Commented"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of action performed",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the action"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of object affected", null=True
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data (changes, metadata, etc.)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="Browser user agent string"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of object affected",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "core_activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_activi_user_id_0351b4_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_activi_content_02b503_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_activi_action_4c98f2_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_activi_created_591ace_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ERPReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.BigIntegerField(help_text="ID of internal object"),
                ),
                (
                    "erp_number",
                    models.CharField(
                        db_index=True, help_text="ERP document number", max_length=100
                    ),
                ),
                (
                    "erp_line_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Line number within ERP document (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "erp_date",
                    models.DateField(
                        blank=True, help_text="Date of ERP document", null=True
                    ),
                ),
                (
                    "erp_status",
                    models.CharField(
                        blank=True, help_text="Status in ERP system", max_length=50
                    ),
                ),
                (
                    "erp_json_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional ERP metadata as JSON",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Sync"),
                            ("synced", "Synced"),
                            ("error", "Sync Error"),
                            ("manual", "Manual Entry"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("sync_error_message", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of internal object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_erp_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        help_text="Type of ERP document",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="references",
                        to="core_foundation.erpdocumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERP Reference",
                "verbose_name_plural": "ERP References",
                "db_table": "core_erp_reference",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_erp_re_content_6eb4ff_idx",
                    ),
                    models.Index(
                        fields=["erp_number"], name="core_erp_re_erp_num_0f068b_idx"
                    ),
                    models.Index(
                        fields=["document_type", "erp_number"],
                        name="core_erp_re_documen_bb0405_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "erp_number", "erp_line_number"),
                        name="unique_erp_reference",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("effective_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="core_foundation.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="core_foundation.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "core_exchange_rate",
                "ordering": ["-effective_date"],
                "unique_together": {("from_currency", "to_currency", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="LossOfSaleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Internal reference number for this event",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the event", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of what happened"),
                ),
                (
                    "event_date",
                    models.DateField(help_text="Date when the loss event occurred"),
                ),
                (
                    "event_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time when the loss event occurred",
                        null=True,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration of the impact in hours",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "estimated_loss_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated financial loss in local currency",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "calculation_method",
                    models.TextField(
                        blank=True, help_text="How the estimated loss was calculated"
                    ),
                ),
                (
                    "object_id",
                    models.BigIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "affected_customer_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("affected_order_number", models.CharField(blank=True, max_length=100)),
                (
                    "root_cause_analysis",
                    models.TextField(
                        blank=True, help_text="Root cause analysis results"
                    ),
                ),
                (
                    "corrective_actions",
                    models.TextField(
                        blank=True, help_text="Corrective actions taken or planned"
                    ),
                ),
                (
                    "preventive_measures",
                    models.TextField(
                        blank=True, help_text="Preventive measures to avoid recurrence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_loss_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core_foundation.lossofsalecause",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loss_events",
                        to="core_foundation.costcenter",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_loss_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_loss_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loss of Sale Event",
                "verbose_name_plural": "Loss of Sale Events",
                "db_table": "core_loss_of_sale_event",
                "ordering": ["-event_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_date"], name="core_loss_o_event_d_de140b_idx"
                    ),
                    models.Index(
                        fields=["cause"], name="core_loss_o_cause_i_fb8f98_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_loss_o_status_9aa455_idx"
                    ),
                    models.Index(
                        fields=["cost_center"], name="core_loss_o_cost_ce_7a54c8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("TASK", "Task"),
                            ("APPROVAL", "Approval Required"),
                            ("SYSTEM", "System"),
                        ],
                        default="INFO",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Notification priority",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL for the primary action",
                        max_length=500,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        default="View",
                        help_text="Text for the action button",
                        max_length=50,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has read this notification",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "core_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="core_notifi_user_id_f286cd_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="core_notifi_user_id_aa1102_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_notifi_created_f19d5e_idx"
                    ),
                ],
            },
        ),
    ]
