# Generated by Django 5.2.6 on 2025-11-23 00:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jobcard_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique job card code (used in QR codes)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("NEW_BUILD", "New Build"),
                            ("REPAIR", "Repair"),
                            ("EVALUATION_ONLY", "Evaluation Only"),
                        ],
                        help_text="Derived from work order",
                        max_length=20,
                    ),
                ),
                (
                    "is_repair",
                    models.BooleanField(
                        default=False, help_text="Is this a repair job?"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("RELEASED", "Released"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PAUSED", "Paused"),
                            ("QC_HOLD", "QC Hold"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "current_workstation",
                    models.CharField(
                        blank=True,
                        help_text="Current workstation/machine",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteStepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Order of execution"),
                ),
                (
                    "process_code",
                    models.CharField(
                        help_text="Process identifier (e.g., INFILTRATION, MACHINING, BRAZING)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed step description"),
                ),
                (
                    "default_department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        max_length=30,
                    ),
                ),
                ("default_workstation", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated time to complete (minutes)"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Must this step be completed?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["route", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="BitDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique design code (e.g., HD75WF)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC (Fixed Cutter)"),
                            ("ROLLER_CONE", "Roller Cone"),
                        ],
                        help_text="Type of bit: PDC or Roller Cone",
                        max_length=20,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX", "Matrix (Infiltrated Powder)"),
                            ("STEEL", "Steel (Forged/Machined)"),
                        ],
                        help_text="Body material (relevant for PDC bits)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "size_inch",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Bit diameter in inches (e.g., 12.25)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "blade_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of blades (for PDC bits)",
                        null=True,
                    ),
                ),
                (
                    "nozzle_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of nozzles", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed design description"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this design currently active?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["design_code"],
                "indexes": [
                    models.Index(
                        fields=["bit_type", "active"],
                        name="production__bit_typ_c15958_idx",
                    ),
                    models.Index(
                        fields=["size_inch"], name="production__size_in_a87f3a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BitDesignRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mat_number",
                    models.CharField(
                        db_index=True,
                        help_text="Material/Manufacturing number (MAT number)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(help_text="MAT level (3, 4, 5, etc.)"),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Date this revision becomes effective"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this revision expires (null = current)",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Revision notes and changes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="production.bitdesign",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bit design revisions",
                "ordering": ["-effective_from", "mat_number"],
            },
        ),
        migrations.CreateModel(
            name="BitInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_index=True,
                        help_text="Base serial number (without R1/R2 suffix)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        choices=[
                            ("MATRIX", "Matrix (Infiltrated Powder)"),
                            ("STEEL", "Steel (Forged/Machined)"),
                        ],
                        help_text="Actual body material used",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturing_source",
                    models.CharField(
                        choices=[
                            ("INTERNAL_MATRIX", "Internal Matrix/Infiltration"),
                            ("INTERNAL_STEEL", "Internal Steel Manufacturing"),
                            ("JV_PARTIAL", "Joint Venture Partial/Semi-finished"),
                        ],
                        help_text="Where the body originated",
                        max_length=30,
                    ),
                ),
                (
                    "current_repair_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Repair count: 0=new, 1=R1, 2=R2, etc."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "In Stock"),
                            ("WITH_CUSTOMER", "With Customer"),
                            ("IN_REPAIR", "In Repair"),
                            ("SCRAPPED", "Scrapped"),
                            ("IN_PRODUCTION", "In Production"),
                        ],
                        db_index=True,
                        default="IN_PRODUCTION",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design_revision",
                    models.ForeignKey(
                        help_text="Design revision/MAT number for this bit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="production.bitdesignrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InfiltrationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique batch identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "furnace_id",
                    models.CharField(help_text="Furnace identifier", max_length=50),
                ),
                ("planned_start", models.DateTimeField()),
                ("planned_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "temperature_profile",
                    models.TextField(
                        blank=True,
                        help_text="Temperature profile settings (can be JSON)",
                    ),
                ),
                ("operator_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("LOADING", "Loading"),
                            ("IN_FURNACE", "In Furnace"),
                            ("COOLING", "Cooling"),
                            ("COMPLETED", "Completed"),
                            ("ABORTED", "Aborted"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infiltration_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Infiltration batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InfiltrationBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mold_id",
                    models.CharField(help_text="Mold identifier", max_length=50),
                ),
                (
                    "powder_mix_code",
                    models.CharField(
                        blank=True,
                        help_text="Powder mixture specification",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOADED", "Loaded"),
                            ("IN_FURNACE", "In Furnace"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("REWORK", "Rework"),
                        ],
                        default="LOADED",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.infiltrationbatch",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        help_text="Job card for the matrix body being produced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infiltration_items",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "id"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("evaluator_name", models.CharField(max_length=100)),
                (
                    "overall_condition",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("MINOR_DAMAGE", "Minor Damage"),
                            ("MAJOR_DAMAGE", "Major Damage"),
                            ("SCRAP", "Scrap"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("RETURN_AS_IS", "Return As-Is"),
                            ("REPAIR", "Repair"),
                            ("SCRAP", "Scrap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Evaluation summaries",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="JobPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        help_text="e.g., Waiting material, Waiting QC, Machine breakdown",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="JobRouteStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        max_length=30,
                    ),
                ),
                ("workstation", models.CharField(blank=True, max_length=100)),
                ("process_code", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "operator_name",
                    models.CharField(
                        blank=True,
                        help_text="Operator name if not linked to User",
                        max_length=100,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_steps",
                        to="production.jobcard",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="route_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this step was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.routesteptemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["job_card", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="NDTResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MPI", "Magnetic Particle Inspection"),
                            ("DPI", "Dye Penetrant Inspection"),
                            ("UT", "Ultrasonic Testing"),
                            ("RT", "Radiographic Testing"),
                            ("VT", "Visual Testing"),
                        ],
                        help_text="NDT method used",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                            ("REWORK", "Rework"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inspector_name", models.CharField(max_length=100)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndt_results",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique code encoded in QR",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="production.jobcard",
                    ),
                ),
                (
                    "route_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="production.jobroutestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Route template name (e.g., 'PDC Matrix New Build 12.25')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC (Fixed Cutter)"),
                            ("ROLLER_CONE", "Roller Cone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX", "Matrix (Infiltrated Powder)"),
                            ("STEEL", "Steel (Forged/Machined)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "for_order_type",
                    models.CharField(
                        choices=[
                            ("NEW_BUILD", "New Build"),
                            ("REPAIR", "Repair"),
                            ("EVALUATION_ONLY", "Evaluation Only"),
                        ],
                        help_text="NEW_BUILD, REPAIR, or ANY",
                        max_length=20,
                    ),
                ),
                (
                    "department_focus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        help_text="Primary department for this route",
                        max_length=30,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["bit_type", "active"],
                        name="production__bit_typ_785a3d_idx",
                    ),
                    models.Index(
                        fields=["for_order_type", "active"],
                        name="production__for_ord_9e9a71_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="routesteptemplate",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="production.routetemplate",
            ),
        ),
        migrations.CreateModel(
            name="ThreadInspectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        help_text="e.g., API, premium thread type", max_length=100
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                            ("REWORK", "Rework"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gauge_used",
                    models.CharField(
                        blank=True, help_text="Thread gauge identifier", max_length=100
                    ),
                ),
                ("inspector_name", models.CharField(max_length=100)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_inspections",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wo_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable work order number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("NEW_BUILD", "New Build"),
                            ("REPAIR", "Repair"),
                            ("EVALUATION_ONLY", "Evaluation Only"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("rig", models.CharField(blank=True, max_length=100)),
                ("well", models.CharField(blank=True, max_length=100)),
                ("field", models.CharField(blank=True, max_length=100)),
                (
                    "rent_or_sale_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RENTAL", "Rental"),
                            ("SALE", "Sale"),
                            ("TRIAL", "Trial"),
                            ("WARRANTY", "Warranty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, help_text="Date bit/order was received", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Target completion date", null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External system reference (ERP, etc.)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing bit (for repairs) or null for new builds",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "design_revision",
                    models.ForeignKey(
                        help_text="Planned design/MAT for this order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="production.bitdesignrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobcard",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_cards",
                to="production.workorder",
            ),
        ),
        migrations.AddField(
            model_name="bitinstance",
            name="initial_build_wo",
            field=models.ForeignKey(
                blank=True,
                help_text="Initial build work order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="built_bits",
                to="production.workorder",
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesignrevision",
            index=models.Index(
                fields=["design", "active"], name="production__design__5db750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesignrevision",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="production__effecti_5d46ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="infiltrationbatch",
            index=models.Index(
                fields=["status", "furnace_id"], name="production__status_1b31b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infiltrationbatch",
            index=models.Index(
                fields=["planned_start"], name="production__planned_99bfb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infiltrationbatchitem",
            index=models.Index(
                fields=["batch", "status"], name="production__batch_i_58c8ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpause",
            index=models.Index(
                fields=["job_card", "start_time"], name="production__job_car_7f8f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ndtresult",
            index=models.Index(
                fields=["job_card", "method"], name="production__job_car_30fb85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobroutestep",
            index=models.Index(
                fields=["job_card", "status"], name="production__job_car_2c8e61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobroutestep",
            index=models.Index(
                fields=["status", "department"], name="production__status_42c931_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobroutestep",
            unique_together={("job_card", "sequence")},
        ),
        migrations.AddIndex(
            model_name="routesteptemplate",
            index=models.Index(
                fields=["route", "sequence"], name="production__route_i_ed9b69_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routesteptemplate",
            unique_together={("route", "sequence")},
        ),
        migrations.AddIndex(
            model_name="threadinspectionresult",
            index=models.Index(
                fields=["job_card", "result"], name="production__job_car_02c3c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["status", "priority"], name="production__status_0ca31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["order_type", "status"], name="production__order_t_3ed836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["customer_name"], name="production__custome_c30369_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["due_date"], name="production__due_dat_913a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["status", "department"], name="production__status_64fde0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["work_order", "status"], name="production__work_or_a84c4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitinstance",
            index=models.Index(
                fields=["status", "manufacturing_source"],
                name="production__status_8b4e12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bitinstance",
            index=models.Index(
                fields=["design_revision", "body_material"],
                name="production__design__21e9fc_idx",
            ),
        ),
    ]
