# Generated by Django 5.2.6 on 2025-11-23 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NonConformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ncr_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique NCR number (e.g., NCR-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("PENDING_MRB", "Pending MRB Decision"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "detected_at_process",
                    models.CharField(
                        help_text="Process where issue was detected (e.g., BRAZING, NDT_INSPECTION)",
                        max_length=100,
                    ),
                ),
                ("detected_by", models.CharField(max_length=100)),
                (
                    "detected_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the non-conformance"
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True,
                        help_text="Root cause analysis (filled after investigation)",
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(
                        blank=True, help_text="Corrective action taken or planned"
                    ),
                ),
                (
                    "preventive_action",
                    models.TextField(
                        blank=True, help_text="Preventive action to avoid recurrence"
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USE_AS_IS", "Use As-Is"),
                            ("USE_AS_IS_DEVIATION", "Use As-Is with Deviation"),
                            ("REWORK", "Rework"),
                            ("REPAIR", "Repair"),
                            ("SCRAP", "Scrap"),
                            ("RETURN_SUPPLIER", "Return to Supplier"),
                            ("DOWNGRADE", "Downgrade"),
                        ],
                        help_text="MRB disposition decision",
                        max_length=30,
                    ),
                ),
                (
                    "disposition_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of MRB decision", null=True
                    ),
                ),
                (
                    "disposition_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who made disposition decision",
                        max_length=100,
                    ),
                ),
                (
                    "disposition_notes",
                    models.TextField(
                        blank=True, help_text="Disposition justification and notes"
                    ),
                ),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_cost_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost impact (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Affected bit instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related job card (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncrs",
                        to="production.jobcard",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related work order",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncrs",
                        to="production.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Non-Conformance Report",
                "verbose_name_plural": "Non-Conformance Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hold_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique hold identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "hold_reason",
                    models.CharField(
                        choices=[
                            ("WAIT_MATERIAL", "Waiting for Material"),
                            ("WAIT_QC", "Waiting for QC/Inspection"),
                            ("WAIT_ENG", "Waiting for Engineering Decision"),
                            ("MACHINE_DOWN", "Machine Breakdown"),
                            ("TOOL_UNAVAIL", "Tool/Fixture Unavailable"),
                            ("CUSTOMER_HOLD", "Customer Hold"),
                            ("QUALITY_ISSUE", "Quality Issue Under Investigation"),
                            ("DESIGN_CHANGE", "Design Change Pending"),
                            ("NO_OPERATOR", "Operator Unavailable"),
                            ("FURNACE_UNAVAIL", "Furnace Unavailable"),
                            ("POWER_OUTAGE", "Power Outage"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("hold_initiated_by", models.CharField(max_length=100)),
                ("hold_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("hold_end", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of hold reason"),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, help_text="How the hold was resolved"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Does this hold require management approval to release?",
                    ),
                ),
                (
                    "approved_for_release_by",
                    models.CharField(blank=True, max_length=100),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_delay_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated production delay in hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cost_impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost impact (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_holds",
                        to="production.jobcard",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_holds",
                        to="production.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Hold",
                "verbose_name_plural": "Production Holds",
                "ordering": ["-hold_start"],
            },
        ),
        migrations.CreateModel(
            name="ReworkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rework_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique rework record number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "rework_reason",
                    models.CharField(
                        choices=[
                            ("DIM_OUT_SPEC", "Dimension Out of Specification"),
                            ("SURFACE_FINISH", "Surface Finish Issues"),
                            ("THREAD_ISSUES", "Thread Quality Issues"),
                            ("INCOMPLETE_BRAZE", "Incomplete Brazing"),
                            ("HARDFACING_DEFECT", "Hardfacing Defect"),
                            ("WELD_DEFECT", "Welding Defect"),
                            ("CONTAMINATION", "Contamination"),
                            ("INCOMPLETE_PROC", "Incomplete Process Step"),
                            ("COSMETIC", "Cosmetic (Customer Requirement)"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "original_process",
                    models.CharField(
                        help_text="Original process that needs rework (e.g., BRAZING, THREAD_CUTTING)",
                        max_length=100,
                    ),
                ),
                (
                    "rework_description",
                    models.TextField(
                        help_text="Detailed description of rework required"
                    ),
                ),
                (
                    "rework_instructions",
                    models.TextField(help_text="Specific rework instructions"),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("assigned_to_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed (Re-scrap)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_by", models.CharField(blank=True, max_length=100)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "labor_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Labor hours spent on rework",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Additional material cost for rework (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total rework cost (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rework_records",
                        to="production.jobcard",
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_records",
                        to="production.nonconformancereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rework Record",
                "verbose_name_plural": "Rework Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scrap_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique scrap record number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "scrap_reason",
                    models.CharField(
                        choices=[
                            ("QUALITY_FAILURE", "Quality Failure"),
                            ("MATERIAL_DEFECT", "Material Defect"),
                            ("MFG_ERROR", "Manufacturing Error"),
                            ("DAMAGE_PROCESS", "Damage in Process"),
                            ("DESIGN_OBSOLETE", "Design Obsolete"),
                            ("CUSTOMER_REJECT", "Customer Rejection"),
                            (
                                "EXCESSIVE_WEAR",
                                "Excessive Wear (Repair not economical)",
                            ),
                            ("INFILTRATION_FAIL", "Infiltration Failure"),
                            ("BRAZE_FAILURE", "Brazing Failure"),
                            ("CRACK_DETECTED", "Crack Detected (NDT)"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("scrap_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item_description",
                    models.CharField(
                        help_text="What was scrapped (e.g., 'Complete bit', 'Matrix body', '12 PDC cutters')",
                        max_length=200,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Quantity scrapped",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="EA",
                        help_text="Unit of measure (EA, KG, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Material cost lost (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Labor cost invested (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost impact (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        help_text="Manager/supervisor who approved scrap",
                        max_length=100,
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salvage/recovery value (USD)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salvage_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on material recovery (e.g., cutters salvaged, metal recycled)",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scrapped bit instance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_records",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrap_records",
                        to="production.jobcard",
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related NCR if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrap_records",
                        to="production.nonconformancereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrap Record",
                "verbose_name_plural": "Scrap Records",
                "ordering": ["-scrap_date"],
            },
        ),
        migrations.AddIndex(
            model_name="nonconformancereport",
            index=models.Index(
                fields=["status", "severity"], name="production__status_ff65ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformancereport",
            index=models.Index(
                fields=["detected_date"], name="production__detecte_a5c6e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionhold",
            index=models.Index(
                fields=["status", "hold_reason"], name="production__status_b22a96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionhold",
            index=models.Index(
                fields=["hold_start"], name="production__hold_st_cf40a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reworkrecord",
            index=models.Index(
                fields=["status", "rework_reason"], name="production__status_0e2666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reworkrecord",
            index=models.Index(
                fields=["actual_start"], name="production__actual__d7ba2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scraprecord",
            index=models.Index(
                fields=["scrap_date"], name="production__scrap_d_bd66d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scraprecord",
            index=models.Index(
                fields=["scrap_reason"], name="production__scrap_r_b8b976_idx"
            ),
        ),
    ]
