# Generated by Django 5.2.6 on 2025-11-23 03:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0002_nonconformancereport_productionhold_reworkrecord_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee ID (e.g., EMP001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        db_index=True,
                        help_text="Primary department assignment",
                        max_length=30,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "Machine Operator"),
                            ("TECHNICIAN", "Technician"),
                            ("QC_INSPECTOR", "QC Inspector"),
                            ("SUPERVISOR", "Supervisor"),
                            ("ENGINEER", "Engineer"),
                            ("MANAGER", "Manager"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("hire_date", models.DateField(help_text="Employment start date")),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of skills/certifications",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked user account (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="BitRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "release_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique release transaction number (e.g., REL-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready for Dispatch"),
                            ("DISPATCHED", "Dispatched"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "planned_release_date",
                    models.DateField(help_text="Planned dispatch date"),
                ),
                (
                    "actual_release_date",
                    models.DateTimeField(
                        blank=True, help_text="Actual dispatch date/time", null=True
                    ),
                ),
                ("qc_approval_date", models.DateTimeField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "delivery_address",
                    models.TextField(help_text="Full delivery address"),
                ),
                (
                    "customer_contact_name",
                    models.CharField(
                        blank=True, help_text="Customer contact person", max_length=100
                    ),
                ),
                ("customer_contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "transport_company",
                    models.CharField(
                        blank=True, help_text="Shipping company", max_length=200
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Shipment tracking number", max_length=100
                    ),
                ),
                (
                    "awb_number",
                    models.CharField(
                        blank=True,
                        help_text="Air Waybill number (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "delivery_note_number",
                    models.CharField(
                        blank=True, help_text="Delivery note number", max_length=50
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number", max_length=50
                    ),
                ),
                (
                    "certificate_numbers",
                    models.TextField(
                        blank=True, help_text="Quality certificates, test reports, etc."
                    ),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "received_by_customer",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who received at customer site",
                        max_length=100,
                    ),
                ),
                (
                    "customer_signature",
                    models.CharField(
                        blank=True,
                        help_text="Signature reference or file path",
                        max_length=100,
                    ),
                ),
                (
                    "packaging_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Wooden crate, cardboard box, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "number_of_packages",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of packages/parcels"
                    ),
                ),
                (
                    "total_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        help_text="Bit being released",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Associated work order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="production.workorder",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who prepared the release",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_releases",
                        to="production.employee",
                    ),
                ),
                (
                    "qc_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="QC final approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_approved_releases",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Release",
                "verbose_name_plural": "Bit Releases",
                "ordering": ["-planned_release_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BitReceive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique receive transaction number (e.g., RCV-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date/time bit was received",
                    ),
                ),
                (
                    "received_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Name if not linked to Employee",
                        max_length=100,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "transport_company",
                    models.CharField(
                        blank=True,
                        help_text="Shipping/transport company",
                        max_length=200,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Shipment tracking number", max_length=100
                    ),
                ),
                (
                    "package_condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("DAMAGED", "Damaged"),
                            ("POOR", "Poor"),
                        ],
                        default="GOOD",
                        help_text="Condition of packaging",
                        max_length=20,
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Inspection"),
                            ("IN_PROGRESS", "Inspection In Progress"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CONDITIONAL", "Conditional Accept"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateTimeField(blank=True, null=True)),
                (
                    "inspection_notes",
                    models.TextField(
                        blank=True, help_text="Initial inspection observations"
                    ),
                ),
                (
                    "customer_po",
                    models.CharField(
                        blank=True, help_text="Customer PO number", max_length=100
                    ),
                ),
                (
                    "packing_slip",
                    models.CharField(
                        blank=True, help_text="Packing slip number", max_length=100
                    ),
                ),
                (
                    "has_bit_record",
                    models.BooleanField(
                        default=False,
                        help_text="Did bit arrive with usage/drilling record?",
                    ),
                ),
                (
                    "photo_paths",
                    models.TextField(
                        blank=True, help_text="JSON array of photo file paths"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bit instance (for repairs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receives",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Associated work order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receives",
                        to="production.workorder",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="QC inspector",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_receives",
                        to="production.employee",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who received the bit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_bits",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Receive",
                "verbose_name_plural": "Bit Receives",
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="BitLocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_status",
                    models.CharField(
                        choices=[
                            ("IN_TRANSIT_RECEIVING", "In Transit (Receiving)"),
                            ("RECEIVING_INSPECTION", "Receiving Inspection"),
                            ("IN_PRODUCTION", "In Production"),
                            ("QC_HOLD", "QC Hold"),
                            ("READY_FOR_RELEASE", "Ready for Release"),
                            ("IN_TRANSIT_SHIPPING", "In Transit (Shipping)"),
                            ("WITH_CUSTOMER", "With Customer"),
                            ("SCRAPPED", "Scrapped"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "physical_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Warehouse A, Shelf 5' or 'Finishing Dept, Station 3'",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bit_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to="production.bitinstance",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.jobcard",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.workorder",
                    ),
                ),
                (
                    "receive_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.bitreceive",
                    ),
                ),
                (
                    "release_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="production.bitrelease",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_changes",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Location History",
                "verbose_name_plural": "Bit Location Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "status"], name="production__departm_1df9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["role", "status"], name="production__role_2d253e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitrelease",
            index=models.Index(
                fields=["status", "planned_release_date"],
                name="production__status_f7ef88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bitrelease",
            index=models.Index(
                fields=["work_order", "status"], name="production__work_or_98ed7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitrelease",
            index=models.Index(
                fields=["customer_name"], name="production__custome_e8d316_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitreceive",
            index=models.Index(
                fields=["inspection_status", "received_date"],
                name="production__inspect_0da5b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bitreceive",
            index=models.Index(
                fields=["work_order", "received_date"],
                name="production__work_or_d0f353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bitlocationhistory",
            index=models.Index(
                fields=["bit_instance", "-changed_at"],
                name="production__bit_ins_ceee02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bitlocationhistory",
            index=models.Index(
                fields=["location_status", "changed_at"],
                name="production__locatio_fc46d9_idx",
            ),
        ),
    ]
