# Generated by Django 5.2.6 on 2025-11-23 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0003_employee_bitrelease_bitreceive_bitlocationhistory_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Shift"),
                            ("NIGHT", "Night Shift"),
                            ("FULL_DAY", "Full Day"),
                        ],
                        default="FULL_DAY",
                        max_length=20,
                    ),
                ),
                ("jobs_completed", models.PositiveIntegerField(default=0)),
                ("jobs_started", models.PositiveIntegerField(default=0)),
                ("jobs_in_progress", models.PositiveIntegerField(default=0)),
                (
                    "total_processing_time_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_wait_time_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Equipment downtime",
                        max_digits=8,
                    ),
                ),
                (
                    "efficiency_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Processing time / (Processing + Wait + Downtime)",
                        max_digits=5,
                    ),
                ),
                ("quality_holds_count", models.PositiveIntegerField(default=0)),
                ("ncr_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "top_delay_reason",
                    models.CharField(
                        blank=True, help_text="Most common delay reason", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "department"],
                "indexes": [
                    models.Index(
                        fields=["department", "-date"],
                        name="production__departm_e7e801_idx",
                    )
                ],
                "unique_together": {("department", "date", "shift")},
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique equipment ID (e.g., INFIL-01, LATHE-03)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "equipment_type",
                    models.CharField(
                        help_text="e.g., Infiltration Furnace, CNC Lathe, Welding Station",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in facility", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("BREAKDOWN", "Broken Down"),
                            ("IDLE", "Idle"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        db_index=True,
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled preventive maintenance",
                        null=True,
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.PositiveIntegerField(
                        default=90, help_text="Days between preventive maintenance"
                    ),
                ),
                (
                    "total_operating_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["department", "equipment_code"],
                "indexes": [
                    models.Index(
                        fields=["department", "status"],
                        name="production__departm_1a3cb2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessAverageTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_code", models.CharField(db_index=True, max_length=100)),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC (Fixed Cutter)"),
                            ("ROLLER_CONE", "Roller Cone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX", "Matrix (Infiltrated Powder)"),
                            ("STEEL", "Steel (Forged/Machined)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bit_size_inch", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "avg_setup_time_minutes",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "avg_processing_time_minutes",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "avg_wait_time_minutes",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "avg_total_time_minutes",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "std_dev_processing_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(
                        help_text="Number of samples in average"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["process_code", "bit_type", "bit_size_inch"],
                "indexes": [
                    models.Index(
                        fields=["process_code", "bit_type"],
                        name="production__process_eaf663_idx",
                    )
                ],
                "unique_together": {
                    ("process_code", "bit_type", "body_material", "bit_size_inch")
                },
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique request number (e.g., MAINT-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("BREAKDOWN", "Breakdown/Emergency"),
                            ("PREVENTIVE", "Preventive Maintenance"),
                            ("CALIBRATION", "Calibration"),
                            ("UPGRADE", "Upgrade/Modification"),
                            ("INSPECTION", "Inspection"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical - Production Stopped"),
                            ("HIGH", "High - Affecting Performance"),
                            ("MEDIUM", "Medium - Schedule Soon"),
                            ("LOW", "Low - Routine"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING_PARTS", "Waiting for Parts"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("reported_by_name", models.CharField(blank=True, max_length=100)),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "problem_description",
                    models.TextField(help_text="Detailed description of the problem"),
                ),
                (
                    "impact_on_production",
                    models.TextField(
                        blank=True, help_text="How this affects production"
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("work_started_at", models.DateTimeField(blank=True, null=True)),
                ("work_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "work_performed",
                    models.TextField(blank=True, help_text="Description of work done"),
                ),
                (
                    "parts_used",
                    models.TextField(blank=True, help_text="Parts and materials used"),
                ),
                (
                    "labor_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "parts_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "downtime_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="When equipment became unavailable",
                        null=True,
                    ),
                ),
                (
                    "downtime_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When equipment returned to service",
                        null=True,
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total downtime in hours",
                        max_digits=8,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_job_cards",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Job cards delayed by this maintenance",
                        related_name="affected_by_maintenance",
                        to="production.jobcard",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Maintenance technician assigned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to="production.employee",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="production.equipment",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who reported the issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_reports",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="production__status_f4575b_idx",
                    ),
                    models.Index(
                        fields=["equipment", "status"],
                        name="production__equipme_a20695_idx",
                    ),
                    models.Index(
                        fields=["-reported_at"], name="production__reporte_cbfd4f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessTimeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_code", models.CharField(db_index=True, max_length=100)),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("PDC", "PDC (Fixed Cutter)"),
                            ("ROLLER_CONE", "Roller Cone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX", "Matrix (Infiltrated Powder)"),
                            ("STEEL", "Steel (Forged/Machined)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bit_size_inch",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Bit diameter for grouping metrics",
                        max_digits=5,
                    ),
                ),
                ("blade_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "setup_time_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Time to setup for process",
                        max_digits=8,
                    ),
                ),
                (
                    "processing_time_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual processing time",
                        max_digits=8,
                    ),
                ),
                (
                    "wait_time_before_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Waiting time before process started",
                        max_digits=8,
                    ),
                ),
                (
                    "total_time_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total time from arrival to completion",
                        max_digits=8,
                    ),
                ),
                ("workstation", models.CharField(blank=True, max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "delay_reason",
                    models.CharField(
                        blank=True, help_text="Reason for delays if any", max_length=200
                    ),
                ),
                (
                    "had_issues",
                    models.BooleanField(
                        default=False, help_text="Were there any issues during process?"
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_metrics",
                        to="production.jobcard",
                    ),
                ),
                (
                    "job_route_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_metric",
                        to="production.jobroutestep",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_metrics",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["process_code", "bit_type", "bit_size_inch"],
                        name="production__process_80ee5b_idx",
                    ),
                    models.Index(
                        fields=["department", "completed_at"],
                        name="production__departm_cb9abd_idx",
                    ),
                    models.Index(
                        fields=["operator", "completed_at"],
                        name="production__operato_8d58a9_idx",
                    ),
                ],
            },
        ),
    ]
