# Generated by Django 5.2.6 on 2025-11-23 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_departmentkpi_equipment_processaveragetime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique correction request number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("requested_by_name", models.CharField(blank=True, max_length=100)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("REVERSE_STEP", "Reverse Step - Mark as Not Done"),
                            ("CHANGE_OPERATOR", "Change Operator Assignment"),
                            ("ADJUST_TIMES", "Adjust Recorded Times"),
                            ("CANCEL_EXECUTION", "Cancel Wrong Execution"),
                        ],
                        default="REVERSE_STEP",
                        max_length=30,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why does this need to be corrected?"),
                ),
                (
                    "impact_description",
                    models.TextField(
                        blank=True, help_text="What is the impact of this mistake?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Supervisor Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Correction Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("supervisor_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor_decision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Supervisor's comments on approval/rejection",
                    ),
                ),
                (
                    "corrected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the correction was actually performed",
                        null=True,
                    ),
                ),
                (
                    "correction_notes",
                    models.TextField(
                        blank=True, help_text="Notes about what was done to correct"
                    ),
                ),
                (
                    "original_step_status",
                    models.CharField(
                        blank=True,
                        help_text="Original status of the route step before correction",
                        max_length=20,
                    ),
                ),
                (
                    "original_operator_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="How urgent is this correction?",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who performed the correction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_corrections",
                        to="production.employee",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="production.jobcard",
                    ),
                ),
                (
                    "job_route_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="production.jobroutestep",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_correction_requests",
                        to="production.employee",
                    ),
                ),
                (
                    "supervisor_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_correction_requests",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Correction Request",
                "verbose_name_plural": "Process Correction Requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique execution log number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("process_code", models.CharField(max_length=100)),
                ("operator_name", models.CharField(blank=True, max_length=100)),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "was_valid_sequence",
                    models.BooleanField(
                        default=True,
                        help_text="Was this the correct next step in sequence?",
                    ),
                ),
                (
                    "expected_process_code",
                    models.CharField(
                        blank=True,
                        help_text="What process code was expected (if not valid)",
                        max_length=100,
                    ),
                ),
                (
                    "validation_message",
                    models.TextField(blank=True, help_text="Validation result message"),
                ),
                ("workstation", models.CharField(blank=True, max_length=100)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MATRIX_INFILTRATION", "Matrix/Infiltration Department"),
                            ("FINISHING", "Finishing Department"),
                            ("REPAIR", "Repair Department"),
                            ("QC", "Quality Control"),
                            ("ASSEMBLY", "Assembly"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "was_corrected",
                    models.BooleanField(
                        default=False,
                        help_text="Was this execution later corrected/reversed?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correction_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrected_executions",
                        to="production.processcorrectionrequest",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="production.jobcard",
                    ),
                ),
                (
                    "job_route_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="production.jobroutestep",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_executions",
                        to="production.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Execution Log",
                "verbose_name_plural": "Process Execution Logs",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.AddField(
            model_name="processcorrectionrequest",
            name="execution_log",
            field=models.ForeignKey(
                blank=True,
                help_text="The execution log entry being corrected",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correction_requests",
                to="production.processexecutionlog",
            ),
        ),
        migrations.AddIndex(
            model_name="processexecutionlog",
            index=models.Index(
                fields=["job_card", "-scanned_at"],
                name="production__job_car_61995c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processexecutionlog",
            index=models.Index(
                fields=["operator", "-scanned_at"],
                name="production__operato_a80d41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processexecutionlog",
            index=models.Index(
                fields=["was_valid_sequence"], name="production__was_val_b284a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processcorrectionrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="production__status_fc48da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processcorrectionrequest",
            index=models.Index(
                fields=["job_card", "status"], name="production__job_car_0efe8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processcorrectionrequest",
            index=models.Index(
                fields=["requested_by", "-requested_at"],
                name="production__request_125a32_idx",
            ),
        ),
    ]
