# Generated by Django 5.2.6 on 2025-11-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_processcorrectionrequest_processexecutionlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Phone number for operator recognition (unique)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
