# Generated by Django 5.2.6 on 2025-11-23 04:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_add_bom_and_repair_history_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CutterLayoutPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blade_number",
                    models.PositiveIntegerField(
                        help_text="Blade number (1-7 typically)"
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        help_text="Row number from center (1=center, increasing outward)"
                    ),
                ),
                (
                    "position_in_row",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Position within the row (for multiple cutters per row)",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("CONE", "Cone (Center)"),
                            ("SHOULDER", "Shoulder (Middle)"),
                            ("GAUGE", "Gauge (Outer)"),
                            ("NOSE", "Nose (Transition)"),
                        ],
                        help_text="Functional zone on bit face",
                        max_length=20,
                    ),
                ),
                (
                    "cutter_size_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cutter diameter in mm (e.g., 13.00, 16.00, 19.00)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cutter_type",
                    models.CharField(
                        choices=[
                            ("STANDARD_ROUND", "Standard Round PDC"),
                            ("CONICAL", "Conical PDC"),
                            ("RIDGE", "Ridge PDC"),
                            ("STINGER", "Stinger PDC"),
                            ("AXE", "Axe PDC"),
                            ("DOME", "Dome PDC"),
                        ],
                        default="STANDARD_ROUND",
                        help_text="Cutter profile type",
                        max_length=30,
                    ),
                ),
                (
                    "back_rake_angle",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Back rake angle in degrees (0-30°, negative for aggressive)",
                        max_digits=5,
                    ),
                ),
                (
                    "side_rake_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Side rake angle in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "exposure_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cutter exposure above blade in mm",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "radial_position_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance from bit center in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "angular_position_degrees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Angular position on blade (0-360°)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_critical_for_performance",
                    models.BooleanField(
                        default=False, help_text="Critical position (cannot substitute)"
                    ),
                ),
                (
                    "substitution_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Can this cutter be substituted with similar spec?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Special notes for this position"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom_item",
                    models.ForeignKey(
                        help_text="BOM item for this cutter specification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cutter_positions",
                        to="production.bomitem",
                    ),
                ),
                (
                    "design_revision",
                    models.ForeignKey(
                        help_text="Design this layout applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_positions",
                        to="production.bitdesignrevision",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cutter layout positions",
                "ordering": ["blade_number", "row_number", "position_in_row"],
            },
        ),
        migrations.CreateModel(
            name="ActualCutterInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installation_date",
                    models.DateField(
                        blank=True, help_text="Date cutter was installed", null=True
                    ),
                ),
                (
                    "actual_cutter_size_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual cutter size installed",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "actual_cutter_type",
                    models.CharField(
                        choices=[
                            ("STANDARD_ROUND", "Standard Round PDC"),
                            ("CONICAL", "Conical PDC"),
                            ("RIDGE", "Ridge PDC"),
                            ("STINGER", "Stinger PDC"),
                            ("AXE", "Axe PDC"),
                            ("DOME", "Dome PDC"),
                        ],
                        help_text="Actual cutter type installed",
                        max_length=30,
                    ),
                ),
                (
                    "cutter_serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Individual cutter serial number (if tracked)",
                        max_length=100,
                    ),
                ),
                (
                    "cutter_lot_number",
                    models.CharField(
                        blank=True,
                        help_text="Lot/batch number of cutter",
                        max_length=100,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Cutter manufacturer", max_length=200
                    ),
                ),
                (
                    "is_substitution",
                    models.BooleanField(
                        default=False,
                        help_text="True if this differs from design specification",
                    ),
                ),
                (
                    "substitution_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for substitution (material shortage, engineering change, etc.)",
                    ),
                ),
                (
                    "braze_quality_check",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("REWORK", "Rework"),
                            ("NOT_CHECKED", "Not Checked"),
                        ],
                        default="NOT_CHECKED",
                        help_text="Braze quality inspection result",
                        max_length=20,
                    ),
                ),
                (
                    "leak_test_result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("NOT_TESTED", "Not Tested"),
                        ],
                        default="NOT_TESTED",
                        help_text="Leak test result",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTALLED", "Installed"),
                            ("DAMAGED", "Damaged"),
                            ("REPLACED", "Replaced"),
                            ("REMOVED", "Removed"),
                        ],
                        default="INSTALLED",
                        help_text="Current status of this cutter",
                        max_length=20,
                    ),
                ),
                (
                    "removal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date cutter was removed (during repair)",
                        null=True,
                    ),
                ),
                (
                    "removal_reason",
                    models.TextField(blank=True, help_text="Reason for removal"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_bom_item",
                    models.ForeignKey(
                        help_text="Actual BOM item used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actual_installations",
                        to="production.bomitem",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Engineer who approved substitution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cutter_substitutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technician who installed this cutter",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cutter_installations",
                        to="production.employee",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        help_text="Work order (build or repair) this installation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_installations",
                        to="production.workorder",
                    ),
                ),
                (
                    "layout_position",
                    models.ForeignKey(
                        help_text="Design position for this cutter",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actual_installations",
                        to="production.cutterlayoutposition",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "work_order",
                    "layout_position__blade_number",
                    "layout_position__row_number",
                ],
            },
        ),
        migrations.CreateModel(
            name="CutterLayoutRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(
                        help_text="Layout revision number (e.g., LAY-001, LAY-002)",
                        max_length=20,
                    ),
                ),
                (
                    "revision_date",
                    models.DateField(help_text="Date of layout revision"),
                ),
                (
                    "change_description",
                    models.TextField(
                        help_text="Description of what changed in this revision"
                    ),
                ),
                (
                    "reason_for_change",
                    models.TextField(
                        help_text="Why the change was made (field performance, cost reduction, etc.)"
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "effective_from_wo",
                    models.CharField(
                        blank=True,
                        help_text="First work order to use this revision",
                        max_length=50,
                    ),
                ),
                (
                    "field_performance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Field performance feedback for this layout",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Engineer who approved this revision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_layout_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design_revision",
                    models.ForeignKey(
                        help_text="Design this layout revision applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_revisions",
                        to="production.bitdesignrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_date"],
            },
        ),
        migrations.AddIndex(
            model_name="cutterlayoutposition",
            index=models.Index(
                fields=["design_revision", "blade_number"],
                name="production__design__3d9503_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cutterlayoutposition",
            index=models.Index(
                fields=["zone", "cutter_size_mm"], name="production__zone_4d280c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cutterlayoutposition",
            unique_together={
                ("design_revision", "blade_number", "row_number", "position_in_row")
            },
        ),
        migrations.AddIndex(
            model_name="actualcutterinstallation",
            index=models.Index(
                fields=["work_order", "status"], name="production__work_or_02cdef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualcutterinstallation",
            index=models.Index(
                fields=["layout_position", "status"],
                name="production__layout__136f9f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cutterlayoutrevision",
            unique_together={("design_revision", "revision_number")},
        ),
    ]
