# Generated by Django 5.2.6 on 2025-11-24 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_add_cutter_layout_management"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bitdesign",
            options={"ordering": ["bit_type", "size_inch", "current_smi_name"]},
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="connection_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGULAR", "Regular"),
                    ("CEREBRO", "Cerebro"),
                    ("WITH_EROSION_SLEEVE", "With Erosion Sleeve"),
                    ("SHANKLESS", "Shankless"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of connection",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="current_smi_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ARDT / SMI type (e.g., HD75WF, MMD53DH-2)",
                max_length=50,
                verbose_name="Current SMI Name",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="cutter_size_category",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cutter size category (3-8) - auto-derived from name if empty",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="gauge_length_inch",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Gauge length in inches",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Gauge Length (inch)",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="hdbs_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Halliburton design name (e.g., MMD53DH, SF53, EQH12R)",
                max_length=50,
                verbose_name="HDBS Name",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="iadc_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="IADC bit code (e.g., S334, M223, 437, 111)",
                max_length=10,
                verbose_name="IADC Code",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="port_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of ports (can differ from nozzle count)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Free-text human comments and notes about the design",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="bit_type",
            field=models.CharField(
                choices=[("PDC", "PDC (Fixed Cutter)"), ("ROLLER_CONE", "Roller Cone")],
                help_text="Bit Category: Fixed Cutter (PDC) or Roller Cone",
                max_length=20,
                verbose_name="Bit Category (Bit Cat)",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="blade_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of blades (for PDC bits) - auto-derived from name if empty",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MATRIX", "Matrix (Infiltrated Powder)"),
                    ("STEEL", "Steel (Forged/Machined)"),
                ],
                help_text="Body material (Matrix or Steel) - auto-derived from name if empty",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Auto-generated: {size}-{name}-{iadc}. Can be edited manually.",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="design_code",
            field=models.CharField(
                db_index=True,
                help_text="Unique design code (typically same as current_smi_name or hdbs_name)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="size_inch",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Bit diameter in inches (e.g., 8.5, 12.25)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesign",
            index=models.Index(
                fields=["current_smi_name"], name="production__current_430fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesign",
            index=models.Index(
                fields=["hdbs_name"], name="production__hdbs_na_80709a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesign",
            index=models.Index(
                fields=["iadc_code"], name="production__iadc_co_c635a1_idx"
            ),
        ),
    ]
