# Generated by Django 5.2.6 on 2025-11-24 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_add_fc_fields_to_bitdesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitdesignrevision",
            name="previous_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Immediately lower-level MAT for the same design (e.g., Level 4 → Level 3)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_levels",
                to="production.bitdesignrevision",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesignrevision",
            name="level",
            field=models.PositiveSmallIntegerField(
                help_text="Physical bit level (2–6: mold → finished bit)"
            ),
        ),
        migrations.AddIndex(
            model_name="bitdesignrevision",
            index=models.Index(
                fields=["design", "level"], name="production__design__8e1108_idx"
            ),
        ),
    ]
