# Generated by Django 5.2.6 on 2025-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_add_mat_levels_2_6"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitdesign",
            name="breaker_slot_height_inch",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Breaker thickness / axial engagement height in inches.",
                max_digits=5,
                null=True,
                verbose_name="Breaker thickness (inch)",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="breaker_slot_width_inch",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Breaker open width in inches (how thick the breaker key is).",
                max_digits=5,
                null=True,
                verbose_name="Breaker open width (inch)",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="design_mat_number",
            field=models.CharField(
                blank=True,
                help_text="Level-1 MAT number used as the design identifier for this bit family.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="gauge_relief_thou",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Gauge relief on diameter in thou (0 means no relief).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="shank_diameter_inch",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Shank / connection diameter in inches.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesignrevision",
            name="upper_welded",
            field=models.BooleanField(
                blank=True,
                help_text="For Level-5: whether the upper section is already welded (True) or shipped loose (False). Leave blank when not applicable.",
                null=True,
            ),
        ),
    ]
