# Generated by Django 5.2.6 on 2025-11-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0011_add_design_hub_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitdesign",
            name="bit_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STANDARD_FC", "Standard FC"),
                    ("CORE_HEAD_FC", "Core head (FC)"),
                    ("RC", "RC"),
                ],
                help_text="Bit subcategory (Standard FC, Core head, RC)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="connection_end_type",
            field=models.CharField(
                choices=[
                    ("PIN", "Pin (external thread)"),
                    ("BOX", "Box (internal thread)"),
                ],
                default="PIN",
                help_text="Connection end type: pin (external) or box (internal)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="connection_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2 3/8 REG", "2 3/8 REG"),
                    ("2 7/8 REG", "2 7/8 REG"),
                    ("3 1/2 REG", "3 1/2 REG"),
                    ("4 1/2 REG", "4 1/2 REG"),
                    ("5 1/2 REG", "5 1/2 REG"),
                    ("6 5/8 REG", "6 5/8 REG"),
                    ("7 5/8 REG", "7 5/8 REG"),
                    ("8 5/8 REG", "8 5/8 REG"),
                    ("2 3/8 IF", "2 3/8 IF"),
                    ("2 7/8 IF", "2 7/8 IF"),
                    ("3 1/2 IF", "3 1/2 IF"),
                    ("4 IF", "4 IF"),
                    ("4 1/2 IF", "4 1/2 IF"),
                    ("5 IF", "5 IF"),
                    ("5 1/2 IF", "5 1/2 IF"),
                    ("2 7/8 FH", "2 7/8 FH"),
                    ("3 1/2 FH", "3 1/2 FH"),
                    ("4 1/2 FH", "4 1/2 FH"),
                    ("5 1/2 FH", "5 1/2 FH"),
                    ("6 5/8 FH", "6 5/8 FH"),
                ],
                help_text="Bit connection size (API REG/IF/FH, e.g. 4 1/2 REG)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="drift_type",
            field=models.CharField(
                blank=True,
                choices=[("NORMAL", "Standard drift"), ("FULL_DRIFT", "Full drift")],
                help_text="Internal bore type: standard or full drift",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="nozzle_bore_sleeve",
            field=models.BooleanField(
                blank=True,
                help_text="Nozzle bore sleeve used (Yes/No). Null/N/A if nozzle_count=0",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="nozzle_port_size",
            field=models.CharField(
                blank=True,
                help_text="Nozzle port/pocket size. Leave blank or N/A if port_count=0",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="nozzle_size",
            field=models.CharField(
                blank=True,
                help_text="Nozzle orifice size (e.g. 12/32). Leave blank or N/A if nozzle_count=0",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bitdesignrevision",
            name="variant_label",
            field=models.CharField(
                blank=True,
                help_text="Short label for this MAT variant (e.g. 'Texas L3 kit', 'ALT cutter set')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="bitdesignrevision",
            name="variant_notes",
            field=models.TextField(
                blank=True,
                help_text="What distinguishes this MAT from other variants at the same level",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="bit_type",
            field=models.CharField(
                choices=[("PDC", "FC"), ("RC", "RC")],
                help_text="Bit Category: Fixed Cutter (PDC) or Roller Cone",
                max_length=20,
                verbose_name="Bit Category (Bit Cat)",
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("MATRIX", "Matrix"), ("STEEL", "Steel")],
                help_text="Body material (Matrix or Steel) - auto-derived from name if empty",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bitdesign",
            name="design_code",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Auto-filled from SMI/HDBS name",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="bitinstance",
            name="body_material",
            field=models.CharField(
                choices=[("MATRIX", "Matrix"), ("STEEL", "Steel")],
                help_text="Actual body material used",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processaveragetime",
            name="bit_type",
            field=models.CharField(
                choices=[("PDC", "FC"), ("RC", "RC")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="processaveragetime",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("MATRIX", "Matrix"), ("STEEL", "Steel")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processtimemetric",
            name="bit_type",
            field=models.CharField(
                choices=[("PDC", "FC"), ("RC", "RC")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="processtimemetric",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("MATRIX", "Matrix"), ("STEEL", "Steel")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="routetemplate",
            name="bit_type",
            field=models.CharField(
                choices=[("PDC", "FC"), ("RC", "RC")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="routetemplate",
            name="body_material",
            field=models.CharField(
                blank=True,
                choices=[("MATRIX", "Matrix"), ("STEEL", "Steel")],
                max_length=20,
            ),
        ),
    ]
