# Generated by Django 5.2.6 on 2025-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0012_bitdesign_bit_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bitdesign",
            name="entry_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "L1 - Full Design (design specs only)"),
                    (2, "L2 - Tooling (molds, inserts, patterns)"),
                    (3, "L3 - Head + Upper Kit (unwelded, no cutters)"),
                    (4, "L4 - Welded Assembly (no cutters)"),
                    (5, "L5 - With Cutters (brazed, may need finishing)"),
                    (6, "L6 - Ready-to-Run (field-ready bit)"),
                ],
                default=1,
                help_text="The level at which this design enters our manufacturing system",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="entry_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the entry point (e.g., why starting at this level, supplier details)",
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="entry_source",
            field=models.CharField(
                choices=[
                    ("INHOUSE", "In-House Manufacturing"),
                    ("PURCHASED", "Purchased/Acquired"),
                    ("CUSTOMER", "Customer Supplied"),
                    ("REFURB", "Refurbishment"),
                    ("JV", "Joint Venture"),
                ],
                default="INHOUSE",
                help_text="How this design enters our system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bitdesign",
            name="entry_supplier",
            field=models.CharField(
                blank=True,
                help_text="Supplier name if entry_source is PURCHASED or JV",
                max_length=100,
                null=True,
            ),
        ),
    ]
