# Generated by Django 5.2.6 on 2025-11-22 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_foundation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("requires_serial_number", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
                "db_table": "hr_asset_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("requires_renewal", models.BooleanField(default=False)),
                (
                    "renewal_notice_days",
                    models.IntegerField(
                        default=30, help_text="Notify X days before expiry"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "db_table": "hr_document_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HRShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Morning Shift', 'Night Shift', 'Rotating A'",
                        max_length=64,
                        unique=True,
                        verbose_name="Shift Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code for the shift (e.g., 'M', 'N', 'RA')",
                        max_length=16,
                        unique=True,
                        verbose_name="Shift Code",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Shift Start Time")),
                ("end_time", models.TimeField(verbose_name="Shift End Time")),
                (
                    "break_minutes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Break Duration (minutes)",
                    ),
                ),
                (
                    "is_night_shift",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a night shift (for overtime/premium calculations)?",
                        verbose_name="Night Shift",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shift Template",
                "verbose_name_plural": "Shift Templates",
                "db_table": "hr_shift_template",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Leave Type Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Leave Type Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Leave Type Name (Arabic)",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=True,
                        help_text="Is this a paid leave type?",
                        verbose_name="Paid Leave",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True,
                        help_text="Does this leave type require manager approval?",
                        verbose_name="Requires Approval",
                    ),
                ),
                (
                    "max_days_per_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum days allowed per year (leave blank for unlimited)",
                        null=True,
                        verbose_name="Max Days Per Year",
                    ),
                ),
                (
                    "min_notice_days",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum days of advance notice required",
                        verbose_name="Minimum Notice Days",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "db_table": "hr_leave_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="QualificationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "level_order",
                    models.IntegerField(
                        default=0, help_text="For sorting (higher = more advanced)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Qualification Level",
                "verbose_name_plural": "Qualification Levels",
                "db_table": "hr_qualification_level",
                "ordering": ["level_order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duration_hours", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAFETY", "Safety Training"),
                            ("TECHNICAL", "Technical Training"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("COMPLIANCE", "Compliance"),
                            ("LEADERSHIP", "Leadership"),
                            ("OTHER", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
                "db_table": "hr_training_program",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Department code must contain only uppercase letters, numbers, and hyphens.",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                        verbose_name="Department Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Department Name"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اسم القسم بالعربية",
                        max_length=128,
                        verbose_name="Department Name (Arabic)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Finance: Cost center for budgeting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_departments",
                        to="core_foundation.costcenter",
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_departments",
                        to="hr.department",
                        verbose_name="Parent Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "hr_department",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HRAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("description", models.CharField(max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                (
                    "plate_number",
                    models.CharField(
                        blank=True, help_text="For vehicles", max_length=32
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="For phones", max_length=32),
                ),
                (
                    "sim_number",
                    models.CharField(
                        blank=True, help_text="For SIM cards", max_length=32
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="For housing/equipment", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_REPAIR", "In Repair"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hr.assettype"
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Asset",
                "verbose_name_plural": "HR Assets",
                "db_table": "hr_asset",
                "ordering": ["asset_number"],
            },
        ),
        migrations.CreateModel(
            name="HREmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Employee number must contain only uppercase letters, numbers, and hyphens.",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                        verbose_name="Employee Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_PROBATION", "On Probation"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("UNDER_NOTICE", "Under Notice Period"),
                            ("TERMINATED", "Terminated"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="Employment Status",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Hire Date")),
                (
                    "probation_end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date of probation period (if applicable)",
                        null=True,
                        verbose_name="Probation End Date",
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termination Date"
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, verbose_name="Termination Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Finance: Cost center for budgeting and reporting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_employees",
                        to="core_foundation.costcenter",
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Django user account for portal access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "hr_employee",
                "ordering": ["employee_no"],
            },
        ),
        migrations.CreateModel(
            name="HRContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Contract Number",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Employee"),
                            ("FIXED_TERM", "Fixed Term Contract"),
                            ("TEMPORARY", "Temporary"),
                            ("PART_TIME", "Part-Time"),
                            ("INTERN", "Internship"),
                            ("CONSULTANT", "Consultant"),
                            ("CONTRACTOR", "Contractor"),
                        ],
                        max_length=32,
                        verbose_name="Contract Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Contract Start Date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for permanent contracts",
                        null=True,
                        verbose_name="Contract End Date",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Finance: Monthly base salary",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base Salary",
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Finance: Additional allowances as JSON (e.g., {'housing': 1000, 'transport': 500})",
                        verbose_name="Allowances",
                    ),
                ),
                (
                    "working_hours_per_week",
                    models.IntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Working Hours per Week",
                    ),
                ),
                (
                    "shift_pattern",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Shift"),
                            ("NIGHT", "Night Shift"),
                            ("ROTATING", "Rotating Shift"),
                            ("FLEXIBLE", "Flexible"),
                        ],
                        default="DAY",
                        max_length=32,
                        verbose_name="Shift Pattern",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Contract Notes")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only one contract should be active per employee at a time",
                        verbose_name="Active Contract",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Finance: Salary currency",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_foundation.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hr.hremployee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment Contract",
                "verbose_name_plural": "Employment Contracts",
                "db_table": "hr_contract",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=128)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="hr/documents/%Y/%m/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.documenttype",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.hremployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "db_table": "hr_employee_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, verbose_name="Attendance Date"),
                ),
                (
                    "check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check In Time"
                    ),
                ),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check Out Time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("HALF_DAY", "Half Day"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        db_index=True,
                        default="PRESENT",
                        max_length=16,
                        verbose_name="Attendance Status",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes late (if applicable)",
                        verbose_name="Late Minutes",
                    ),
                ),
                (
                    "overtime_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Overtime minutes worked",
                        verbose_name="Overtime Minutes",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("IMPORTED", "Imported from File"),
                            ("WHATSAPP", "WhatsApp Integration"),
                            ("TIME_CLOCK", "Time Clock System"),
                            ("QR_SCAN", "QR Code Scan"),
                        ],
                        default="MANUAL",
                        max_length=32,
                        verbose_name="Data Source",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.hremployee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "hr_attendance_record",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("condition_at_assignment", models.TextField(blank=True)),
                ("condition_at_return", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.hrasset",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="hr.hremployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Assignment",
                "verbose_name_plural": "Asset Assignments",
                "db_table": "hr_asset_assignment",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="HRPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name_en",
                    models.CharField(
                        help_text="First name in English",
                        max_length=120,
                        verbose_name="First Name (English)",
                    ),
                ),
                (
                    "middle_name_en",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Middle name in English (optional)",
                        max_length=120,
                        verbose_name="Middle Name (English)",
                    ),
                ),
                (
                    "last_name_en",
                    models.CharField(
                        help_text="Last name in English",
                        max_length=120,
                        verbose_name="Last Name (English)",
                    ),
                ),
                (
                    "first_name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="الاسم الأول بالعربية",
                        max_length=120,
                        verbose_name="First Name (Arabic)",
                    ),
                ),
                (
                    "middle_name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="الاسم الأوسط بالعربية",
                        max_length=120,
                        verbose_name="Middle Name (Arabic)",
                    ),
                ),
                (
                    "last_name_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اسم العائلة بالعربية",
                        max_length=120,
                        verbose_name="Last Name (Arabic)",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "nationality_iso2",
                    models.CharField(
                        default="SA",
                        help_text="ISO 3166-1 alpha-2 country code (SA, US, IN, etc.)",
                        max_length=2,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_index=True,
                        help_text="National ID number (always required)",
                        max_length=64,
                        unique=True,
                        verbose_name="National ID",
                    ),
                ),
                (
                    "iqama_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Iqama number (required for non-Saudi nationals)",
                        max_length=10,
                        verbose_name="Iqama Number",
                    ),
                ),
                (
                    "iqama_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Iqama Expiry Date"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hr/people/photos/%Y/%m/",
                        verbose_name="Photo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_people",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "hr_person",
                "ordering": ["last_name_en", "first_name_en"],
            },
        ),
        migrations.AddField(
            model_name="hremployee",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employment",
                to="hr.hrperson",
                verbose_name="Person",
            ),
        ),
        migrations.CreateModel(
            name="HREmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("WORK", "Work"),
                            ("OTHER", "Other"),
                        ],
                        default="PERSONAL",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="hr.hrperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Address",
                "verbose_name_plural": "Email Addresses",
                "db_table": "hr_email",
                "ordering": ["-is_primary", "email_type"],
            },
        ),
        migrations.CreateModel(
            name="HRPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile"),
                            ("HOME", "Home"),
                            ("WORK", "Work"),
                            ("EMERGENCY", "Emergency Contact"),
                        ],
                        default="MOBILE",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_whatsapp", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="hr.hrperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Number",
                "verbose_name_plural": "Phone Numbers",
                "db_table": "hr_phone",
                "ordering": ["-is_primary", "phone_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "days_count",
                    models.IntegerField(
                        help_text="Total number of leave days (auto-calculated)",
                        verbose_name="Number of Days",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for leave request",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link to approval workflow from core_foundation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core_foundation.approvaltype",
                        verbose_name="Approval Type",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.hremployee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr.leavetype",
                        verbose_name="Leave Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "hr_leave_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Position code must contain only uppercase letters, numbers, and hyphens.",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                        verbose_name="Position Code",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Position Title"),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="المسمى الوظيفي بالعربية",
                        max_length=128,
                        verbose_name="Position Title (Arabic)",
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., 'L3', 'M2', 'S1' for internal classification",
                        max_length=16,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORKER", "Worker"),
                            ("TECHNICIAN", "Technician"),
                            ("ENGINEER", "Engineer"),
                            ("SUPERVISOR", "Supervisor"),
                            ("MANAGER", "Manager"),
                            ("EXECUTIVE", "Executive"),
                            ("ADMINISTRATIVE", "Administrative"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="Position Category",
                    ),
                ),
                (
                    "is_supervisory",
                    models.BooleanField(
                        default=False,
                        help_text="Does this position supervise other employees?",
                        verbose_name="Supervisory Position",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Position Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "hr_position",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="hr_position_code_878671_idx"),
                    models.Index(
                        fields=["category"], name="hr_position_categor_0ef8d7_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="hr_position_is_acti_06fa33_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="hremployee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="hr.position",
                verbose_name="Position",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "qualification_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hr.qualificationlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Qualification",
                "verbose_name_plural": "Employee Qualifications",
                "db_table": "hr_employee_qualification",
                "ordering": ["-completion_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("trainer", models.CharField(blank=True, max_length=200)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="hr.trainingprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Session",
                "verbose_name_plural": "Training Sessions",
                "db_table": "hr_training_session",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("passed", models.BooleanField(default=False)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="hr.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Training Record",
                "verbose_name_plural": "Employee Training Records",
                "db_table": "hr_employee_training",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="hr_departme_code_d27daf_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="hr_departme_is_acti_b443d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrcontract",
            index=models.Index(
                fields=["employee", "is_active"], name="hr_contract_employe_577740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrcontract",
            index=models.Index(
                fields=["start_date", "end_date"], name="hr_contract_start_d_6ecd31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["employee", "date"], name="hr_attendan_employe_deb7cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["date", "status"], name="hr_attendan_date_c2ed97_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="hrperson",
            index=models.Index(
                fields=["national_id"], name="hr_person_nationa_955cf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrperson",
            index=models.Index(
                fields=["iqama_number"], name="hr_person_iqama_n_356e57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrperson",
            index=models.Index(
                fields=["last_name_en", "first_name_en"],
                name="hr_person_last_na_84a9aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="hr_leave_re_employe_5480af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["status", "start_date"], name="hr_leave_re_status_05ed82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["leave_type", "status"], name="hr_leave_re_leave_t_745ca0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hremployee",
            index=models.Index(
                fields=["employee_no"], name="hr_employee_employe_3b1fdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hremployee",
            index=models.Index(fields=["status"], name="hr_employee_status_75bd6c_idx"),
        ),
        migrations.AddIndex(
            model_name="hremployee",
            index=models.Index(
                fields=["department", "status"], name="hr_employee_departm_fe730b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeetraining",
            unique_together={("employee", "session")},
        ),
    ]
