# Generated by Django 5.2.6 on 2025-11-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter Request"),
                            ("DOCUMENT", "Document Request"),
                            ("DATA_UPDATE", "Personal Data Update"),
                            ("CERTIFICATE", "Certificate Request"),
                            ("OTHER", "Other Request"),
                        ],
                        max_length=32,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Request Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Handled Date"
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(blank=True, verbose_name="HR Response Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_requests",
                        to="hr.hremployee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handled By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Request",
                "verbose_name_plural": "Employee Requests",
                "db_table": "hr_portal_employee_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="hr_portal_e_employe_446b2c_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="hr_portal_e_status_c13770_idx",
                    ),
                ],
            },
        ),
    ]
