# Generated by Django 5.2.6 on 2025-11-23 00:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., NEW, USED, REPAIRABLE, SCRAP",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Condition Type",
                "verbose_name_plural": "Condition Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OwnershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., OWN, CUSTOMER, CONSIGNMENT, JV_OWNED",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ownership Type",
                "verbose_name_plural": "Ownership Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique supplier code", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, help_text="e.g., Net 30, Net 60", max_length=200
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., EA, KG, L, M", max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Each, Kilogram, Liter, Meter", max_length=100
                    ),
                ),
                (
                    "is_base_unit",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the base unit for conversions?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique warehouse code", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique category code", max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Cutters, Matrix Powder, Steel Forgings",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.itemcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Category",
                "verbose_name_plural": "Item Categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        help_text="Unique item code", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("CUTTER", "PDC Cutter"),
                            ("MATRIX_POWDER", "Matrix Powder"),
                            ("BINDER", "Binder"),
                            ("STEEL_BODY", "Steel Body/Forging"),
                            ("JV_PARTIAL_BODY", "JV Semi-finished Body"),
                            ("UPPER_SECTION", "Upper Section (API Connection)"),
                            ("HARDFACING_POWDER", "Hardfacing Powder"),
                            ("FLUX", "Flux"),
                            ("BRAZING_ALLOY", "Brazing Alloy"),
                            ("CONSUMABLE", "Consumable"),
                            ("TOOL", "Tool"),
                            ("SPARE_PART", "Spare Part"),
                            ("GAS", "Gas"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of item",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum stock level before reorder",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, help_text="External ERP reference", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Item category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.itemcategory",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred supplier for this item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_items",
                        to="inventory.supplier",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        help_text="Primary unit of measure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["item_code"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., CUTTER-RACK-01, POWDER-SILO-1", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False,
                        help_text="Virtual location for adjustments, scrap, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Parent warehouse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["warehouse__code", "code"],
                "unique_together": {("warehouse", "code")},
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "condition_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_levels",
                        to="inventory.conditiontype",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.location",
                    ),
                ),
                (
                    "ownership_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_levels",
                        to="inventory.ownershiptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Level",
                "verbose_name_plural": "Stock Levels",
                "indexes": [
                    models.Index(
                        fields=["item", "location"],
                        name="inventory_s_item_id_dec145_idx",
                    ),
                    models.Index(
                        fields=["item"], name="inventory_s_item_id_fb3b61_idx"
                    ),
                ],
                "unique_together": {
                    ("item", "location", "condition_type", "ownership_type")
                },
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_RECEIPT", "Purchase Receipt"),
                            ("ISSUE_TO_PRODUCTION", "Issue to Production"),
                            ("RETURN_FROM_PRODUCTION", "Return from Production"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("SCRAP", "Scrap"),
                            ("INITIAL_STOCK", "Initial Stock"),
                        ],
                        help_text="Type of stock transaction",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity moved",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number (PO, JobCard, WO, etc.)",
                        max_length=100,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, help_text="External ERP reference", max_length=100
                    ),
                ),
                (
                    "condition_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.conditiontype",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source location (null for receipts)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_from",
                        to="inventory.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.item",
                    ),
                ),
                (
                    "ownership_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.ownershiptype",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination location (null for issues)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_to",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-performed_at"],
                        name="inventory_s_item_id_522359_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-performed_at"],
                        name="inventory_s_transac_7030aa_idx",
                    ),
                ],
            },
        ),
    ]
