# Generated by Django 5.2.6 on 2025-11-23 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_view",
                    models.CharField(
                        choices=[
                            ("enhanced", "Enhanced Dashboard with Charts"),
                            ("basic", "Basic Dashboard"),
                        ],
                        default="enhanced",
                        help_text="Default dashboard view",
                        max_length=20,
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        choices=[
                            (10, "10 items"),
                            (20, "20 items"),
                            (50, "50 items"),
                            (100, "100 items"),
                        ],
                        default=20,
                        help_text="Number of items to display per page in lists",
                    ),
                ),
                (
                    "receive_low_stock_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for low stock items",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=25,
                        help_text="Alert when stock falls below this percentage of reorder level",
                    ),
                ),
                (
                    "default_export_format",
                    models.CharField(
                        choices=[("excel", "Excel (.xlsx)"), ("csv", "CSV (.csv)")],
                        default="excel",
                        help_text="Preferred export file format",
                        max_length=10,
                    ),
                ),
                (
                    "show_qr_codes",
                    models.BooleanField(
                        default=True,
                        help_text="Show QR code buttons in item and location lists",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Preferred language",
                        max_length=10,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("YYYY-MM-DD", "YYYY-MM-DD (2025-01-15)"),
                            ("DD/MM/YYYY", "DD/MM/YYYY (15/01/2025)"),
                            ("MM/DD/YYYY", "MM/DD/YYYY (01/15/2025)"),
                        ],
                        default="YYYY-MM-DD",
                        help_text="Preferred date format",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
