# Generated by Django 5.2.6 on 2025-11-23 04:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stockoperationapproval"),
        ("purchasing", "0002_goodsreturn_goodsreturnline_grncorrection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=100, unique=True)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Use for items with expiration (chemicals, consumables, etc.)",
                        null=True,
                    ),
                ),
                (
                    "shelf_life_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Shelf life in days from manufacturing date",
                        null=True,
                    ),
                ),
                ("supplier_batch_number", models.CharField(blank=True, max_length=100)),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Quality certificate number",
                        max_length=100,
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True, help_text="URL to certificate document"
                    ),
                ),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False,
                        help_text="True if batch is under quarantine/inspection",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False, help_text="Manually marked as expired"
                    ),
                ),
                (
                    "is_recalled",
                    models.BooleanField(default=False, help_text="Supplier recall"),
                ),
                ("recall_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.item",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Batch",
                "verbose_name_plural": "Item Batches",
                "ordering": ["expiry_date", "batch_number"],
            },
        ),
        migrations.CreateModel(
            name="ExpiredItemAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_number", models.CharField(max_length=50, unique=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DISPOSE", "Dispose/Destroy"),
                            ("WRITE_OFF", "Write Off"),
                            ("RETURN_VENDOR", "Return to Vendor"),
                            ("DONATE", "Donate"),
                            ("SELL_DISCOUNT", "Sell at Discount"),
                            ("EXTEND_LIFE", "Extend Shelf Life (with approval)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "book_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Book value of expired items",
                        max_digits=15,
                    ),
                ),
                (
                    "recovery_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount recovered (if any)",
                        max_digits=15,
                    ),
                ),
                (
                    "loss_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net loss amount",
                        max_digits=15,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "disposal_certificate",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number for disposal",
                        max_length=100,
                    ),
                ),
                ("documentation_url", models.URLField(blank=True)),
                (
                    "reason",
                    models.TextField(help_text="Reason for expiry/action taken"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expiry_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expiry_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expiry_actions",
                        to="inventory.itembatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expired Item Action",
                "verbose_name_plural": "Expired Item Actions",
                "ordering": ["-action_date", "-action_number"],
            },
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_number", models.CharField(max_length=50, unique=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("RECEIVING", "Receiving Inspection"),
                            ("IN_PROCESS", "In-Process Inspection"),
                            ("FINAL", "Final Inspection"),
                            ("PERIODIC", "Periodic Stock Inspection"),
                            ("CUSTOMER_RETURN", "Customer Return Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateField(default=datetime.date.today)),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Batch/Lot number", max_length=100
                    ),
                ),
                (
                    "quantity_inspected",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "inspection_result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass - Accept"),
                            ("CONDITIONAL", "Conditional Pass - Minor Issues"),
                            ("REWORK", "Rework Required"),
                            ("REJECT", "Reject - Return to Vendor"),
                            ("SCRAP", "Scrap - Unusable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_accepted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantity_rejected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantity_for_rework",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "defect_description",
                    models.TextField(
                        blank=True, help_text="Description of defects found"
                    ),
                ),
                (
                    "defect_category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Dimensional, Visual, Functional, Material",
                        max_length=100,
                    ),
                ),
                (
                    "defect_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRITICAL", "Critical - Safety/Function Impact"),
                            ("MAJOR", "Major - Performance Impact"),
                            ("MINOR", "Minor - Aesthetic Only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True)),
                (
                    "photo_url",
                    models.URLField(blank=True, help_text="URL to defect photos"),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, help_text="Actions taken based on inspection result"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to="purchasing.goodsreceiptline",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Inspection",
                "verbose_name_plural": "Quality Inspections",
                "ordering": ["-inspection_date", "-inspection_number"],
            },
        ),
        migrations.CreateModel(
            name="DefectiveItemDisposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposition_number", models.CharField(max_length=50, unique=True)),
                (
                    "disposition_type",
                    models.CharField(
                        choices=[
                            ("RETURN_VENDOR", "Return to Vendor"),
                            ("REWORK", "Send for Rework/Repair"),
                            ("SCRAP", "Scrap - Destroy"),
                            ("DOWNGRADE", "Downgrade - Sell as Second Grade"),
                            ("USE_AS_IS", "Use As-Is (with concession)"),
                            ("HOLD", "Hold for Further Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Disposition"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estimated_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated financial loss",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "recovery_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value recovered (if sold as scrap/downgrade)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("disposition_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "rework_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "return_authorization",
                    models.CharField(
                        blank=True,
                        help_text="RMA or return authorization number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rework_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Location where rework is performed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_items",
                        to="inventory.location",
                    ),
                ),
                (
                    "quality_inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispositions",
                        to="inventory.qualityinspection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defective Item Disposition",
                "verbose_name_plural": "Defective Item Dispositions",
                "ordering": ["-disposition_date", "-disposition_number"],
            },
        ),
        migrations.CreateModel(
            name="StockLevelExtended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Quality Approved"),
                            ("QUARANTINE", "Under Quarantine"),
                            ("REJECTED", "Quality Rejected"),
                            ("REWORK", "In Rework"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Restricted use (e.g., for specific project only)",
                    ),
                ),
                ("restriction_reason", models.TextField(blank=True)),
                ("near_expiry_alert_sent", models.BooleanField(default=False)),
                ("last_alert_date", models.DateField(blank=True, null=True)),
                (
                    "stock_level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_info",
                        to="inventory.stocklevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Level Extended Info",
                "verbose_name_plural": "Stock Level Extended Info",
            },
        ),
        migrations.CreateModel(
            name="UsedItemTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Unique serial number for this specific item",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("original_purchase_date", models.DateField(blank=True, null=True)),
                (
                    "original_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_book_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current depreciated value",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A - Excellent (Like New)"),
                            ("B", "Grade B - Good (Minor Wear)"),
                            ("C", "Grade C - Fair (Visible Wear)"),
                            ("D", "Grade D - Poor (Significant Wear)"),
                            ("R", "Refurbished"),
                        ],
                        max_length=1,
                    ),
                ),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("next_inspection_due", models.DateField(blank=True, null=True)),
                (
                    "hours_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours of usage (for equipment)",
                        max_digits=10,
                    ),
                ),
                (
                    "cycles_used",
                    models.IntegerField(
                        default=0, help_text="Number of usage cycles (for tools)"
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                ("maintenance_notes", models.TextField(blank=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("warranty_terms", models.TextField(blank=True)),
                (
                    "is_serviceable",
                    models.BooleanField(
                        default=True, help_text="Item is in working condition"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Item is available for use"
                    ),
                ),
                (
                    "current_user",
                    models.CharField(
                        blank=True,
                        help_text="Person/department currently using the item",
                        max_length=200,
                    ),
                ),
                ("photo_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_tracking",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Used Item Tracking",
                "verbose_name_plural": "Used Item Tracking",
                "ordering": ["-last_inspection_date", "serial_number"],
            },
        ),
    ]
