# Generated by Django 5.2.6 on 2025-11-23 04:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_itembatch_expireditemaction_qualityinspection_and_more"),
        ("purchasing", "0002_goodsreturn_goodsreturnline_grncorrection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name_arabic",
                    models.CharField(
                        help_text="Company name in Arabic", max_length=200
                    ),
                ),
                (
                    "company_name_english",
                    models.CharField(
                        help_text="Company name in English", max_length=200
                    ),
                ),
                (
                    "commercial_registration",
                    models.CharField(
                        help_text="Commercial Registration (CR) Number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("cr_issue_date", models.DateField(help_text="CR issue date")),
                ("cr_expiry_date", models.DateField(help_text="CR expiry date")),
                (
                    "vat_registration_number",
                    models.CharField(
                        help_text="15-digit Tax Registration Number (TRN)",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="VAT number must be 15 digits starting with 3",
                                regex="^3\\d{14}$",
                            )
                        ],
                    ),
                ),
                ("vat_registration_date", models.DateField()),
                (
                    "industrial_license_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "industrial_license_issue_date",
                    models.DateField(blank=True, null=True),
                ),
                ("industrial_license_expiry", models.DateField(blank=True, null=True)),
                (
                    "zakat_certificate_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("zakat_certificate_expiry", models.DateField(blank=True, null=True)),
                (
                    "address_arabic",
                    models.TextField(help_text="Full address in Arabic"),
                ),
                (
                    "address_english",
                    models.TextField(help_text="Full address in English"),
                ),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("building_number", models.CharField(blank=True, max_length=10)),
                ("additional_number", models.CharField(blank=True, max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "einvoice_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable ZATCA E-Invoicing"
                    ),
                ),
                (
                    "einvoice_environment",
                    models.CharField(
                        choices=[
                            ("SANDBOX", "Sandbox/Testing"),
                            ("PRODUCTION", "Production"),
                        ],
                        default="SANDBOX",
                        max_length=20,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Company logo URL for documents"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile (KSA)",
                "verbose_name_plural": "Company Profile (KSA)",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="country_of_origin",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 country code (e.g., SA, CN, US)",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="customs_duty_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Customs duty percentage (for imports)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="hs_code",
            field=models.CharField(
                blank=True,
                help_text="10-digit HS code for customs classification (e.g., 8207.13.00.00)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="requires_saber_certificate",
            field=models.BooleanField(
                default=False, help_text="Item requires SABER certificate for import"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="vat_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Rated - 15%"),
                    ("ZERO_RATED", "Zero Rated - 0%"),
                    ("EXEMPT", "Exempt"),
                    ("OUT_OF_SCOPE", "Out of Scope"),
                ],
                default="STANDARD",
                help_text="VAT treatment type for this item",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomsDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration_number",
                    models.CharField(
                        help_text="FASAH declaration number", max_length=50, unique=True
                    ),
                ),
                (
                    "declaration_type",
                    models.CharField(
                        choices=[
                            ("IMPORT", "Import Declaration"),
                            ("EXPORT", "Export Declaration"),
                            ("RE_EXPORT", "Re-Export Declaration"),
                            ("TEMPORARY", "Temporary Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("declaration_date", models.DateField()),
                (
                    "bill_of_lading",
                    models.CharField(
                        blank=True, help_text="B/L number", max_length=100
                    ),
                ),
                (
                    "airway_bill",
                    models.CharField(
                        blank=True, help_text="AWB number", max_length=100
                    ),
                ),
                ("container_number", models.CharField(blank=True, max_length=50)),
                (
                    "port_of_entry",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Jeddah Islamic Port, King Abdulaziz Port",
                        max_length=100,
                    ),
                ),
                ("port_of_exit", models.CharField(blank=True, max_length=100)),
                (
                    "importer_exporter",
                    models.CharField(help_text="Company name", max_length=200),
                ),
                (
                    "importer_exporter_cr",
                    models.CharField(help_text="CR number", max_length=20),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                (
                    "supplier_country",
                    models.CharField(
                        blank=True, help_text="ISO country code", max_length=2
                    ),
                ),
                ("customs_broker_name", models.CharField(blank=True, max_length=200)),
                (
                    "customs_broker_license",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "total_customs_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total value for customs purposes (CIF)",
                        max_digits=15,
                    ),
                ),
                (
                    "total_customs_duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total customs duty amount",
                        max_digits=15,
                    ),
                ),
                (
                    "total_vat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total VAT on import",
                        max_digits=15,
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Other fees (storage, inspection, etc.)",
                        max_digits=15,
                    ),
                ),
                (
                    "clearance_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Submission"),
                            ("SUBMITTED", "Submitted to Customs"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INSPECTION_REQUIRED", "Inspection Required"),
                            ("CLEARED", "Cleared"),
                            ("HELD", "Held by Customs"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("clearance_date", models.DateField(blank=True, null=True)),
                ("commercial_invoice_url", models.URLField(blank=True)),
                ("packing_list_url", models.URLField(blank=True)),
                ("certificate_of_origin_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customs_declarations",
                        to="purchasing.goodsreceipt",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customs_declarations",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customs Declaration",
                "verbose_name_plural": "Customs Declarations",
                "ordering": ["-declaration_date", "-declaration_number"],
            },
        ),
        migrations.CreateModel(
            name="ItemCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("SABER", "SABER Certificate (Product Conformity)"),
                            ("SFDA", "SFDA Certificate (Food & Drug Authority)"),
                            ("SASO", "SASO Certificate (Saudi Standards)"),
                            ("COO", "Certificate of Origin"),
                            ("COC", "Certificate of Conformity"),
                            ("HALAL", "Halal Certificate"),
                            ("ISO", "ISO Certification"),
                            ("CALIBRATION", "Calibration Certificate"),
                            ("OTHER", "Other Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                (
                    "certificate_name",
                    models.CharField(
                        help_text="Certificate name/title", max_length=200
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Leave blank if certificate doesn't expire"
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Organization that issued certificate", max_length=200
                    ),
                ),
                (
                    "issuing_country",
                    models.CharField(
                        default="SA", help_text="ISO country code", max_length=2
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True, help_text="Link to certificate document/PDF"
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ksa_certificates",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Certificate (KSA)",
                "verbose_name_plural": "Item Certificates (KSA)",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_number", models.CharField(max_length=50, unique=True)),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("SMSA", "SMSA Express"),
                            ("ARAMEX", "Aramex Saudi Arabia"),
                            ("DHL", "DHL Saudi Arabia"),
                            ("FEDEX", "FedEx Saudi Arabia"),
                            ("SPL", "Saudi Post (SPL)"),
                            ("UPS", "UPS Saudi Arabia"),
                            ("ZAJIL", "Zajil Express"),
                            ("NAQEL", "Naqel Express"),
                            ("OTHER", "Other Carrier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "waybill_number",
                    models.CharField(help_text="Tracking/AWB number", max_length=100),
                ),
                ("origin_address", models.TextField()),
                ("origin_city", models.CharField(max_length=100)),
                ("destination_address", models.TextField()),
                ("destination_city", models.CharField(max_length=100)),
                ("recipient_name", models.CharField(max_length=200)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("number_of_packages", models.IntegerField(default=1)),
                (
                    "total_weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Pickup"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("AT_HUB", "At Distribution Hub"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("RETURNED", "Returned to Sender"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "freight_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cod_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash on Delivery amount",
                        max_digits=12,
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, help_text="Carrier tracking URL"),
                ),
                (
                    "delivered_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who received",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="purchasing.goodsreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomsDeclarationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(help_text="Line number in declaration"),
                ),
                (
                    "hs_code",
                    models.CharField(help_text="10-digit HS code", max_length=10),
                ),
                (
                    "description",
                    models.TextField(help_text="Item description for customs"),
                ),
                (
                    "country_of_origin",
                    models.CharField(help_text="ISO country code", max_length=2),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_of_measure",
                    models.CharField(help_text="e.g., KG, PC, M", max_length=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "customs_duty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Customs duty percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "customs_duty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.15"), max_digits=5
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saber_certificate_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "saso_certificate_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customs_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.customsdeclaration",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customs_lines",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customs Declaration Line",
                "verbose_name_plural": "Customs Declaration Lines",
                "ordering": ["customs_declaration", "line_number"],
                "unique_together": {("customs_declaration", "line_number")},
            },
        ),
    ]
