# Generated by Django 5.2.6 on 2025-11-23 03:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_stockoperationapproval"),
        ("purchasing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rtn_number",
                    models.CharField(
                        help_text="Return Number (RTN)", max_length=50, unique=True
                    ),
                ),
                ("return_date", models.DateField(help_text="Date of return")),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("WRONG_ITEM", "Wrong Item Received"),
                            ("WRONG_QUANTITY", "Excess Quantity"),
                            ("DAMAGED", "Damaged on Arrival"),
                            ("DEFECTIVE", "Defective/Quality Issue"),
                            ("NOT_ORDERED", "Not Ordered"),
                            ("EXPIRED", "Expired or Near Expiry"),
                            ("OTHER", "Other Reason"),
                        ],
                        help_text="Reason for return",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to Supplier"),
                            ("APPROVED", "Approved by Supplier"),
                            ("REJECTED", "Rejected by Supplier"),
                            ("PICKED_UP", "Picked Up by Supplier"),
                            ("CREDITED", "Credit Note Received"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True, help_text="Supplier contact person", max_length=200
                    ),
                ),
                (
                    "supplier_approval_ref",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's RMA/approval reference",
                        max_length=100,
                    ),
                ),
                (
                    "credit_note_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's credit note number",
                        max_length=100,
                    ),
                ),
                (
                    "credit_note_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        help_text="Original GRN being returned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchasing.goodsreceipt",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Return",
                "verbose_name_plural": "Goods Returns",
                "ordering": ["-return_date", "-rtn_number"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity being returned",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Unit price for value calculation",
                        max_digits=12,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this return line"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_at_return",
                    models.ForeignKey(
                        help_text="Condition of items being returned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="inventory.conditiontype",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        help_text="Original GRN line being returned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchasing.goodsreceiptline",
                    ),
                ),
                (
                    "goods_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_lines",
                        to="purchasing.goodsreturn",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location from which items are being returned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Return Line",
                "verbose_name_plural": "Goods Return Lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="GRNCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correction_number",
                    models.CharField(
                        help_text="Unique correction reference",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("QUANTITY_OVERCOUNT", "Quantity Overcounted"),
                            ("QUANTITY_UNDERCOUNT", "Quantity Undercounted"),
                            ("WRONG_ITEM", "Wrong Item Recorded"),
                            ("WRONG_LOCATION", "Wrong Location"),
                            ("WRONG_CONDITION", "Wrong Condition Type"),
                            ("OTHER", "Other Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("correction_date", models.DateField()),
                (
                    "original_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original received quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "corrected_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Corrected quantity (if quantity correction)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Detailed reason for correction"),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_grn_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "corrected_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corrected condition (if condition correction)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_corrections",
                        to="inventory.conditiontype",
                    ),
                ),
                (
                    "corrected_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Corrected location (if location correction)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrected_grn_corrections",
                        to="inventory.location",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        help_text="GRN line being corrected",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="purchasing.goodsreceiptline",
                    ),
                ),
                (
                    "original_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="original_grn_corrections",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "GRN Correction",
                "verbose_name_plural": "GRN Corrections",
                "ordering": ["-correction_date", "-correction_number"],
            },
        ),
    ]
